version: "3.9"
services:
  zmq-rep-mod:
    build:
      context: ../ZMQ-mod
      dockerfile: Dockerfile
    container_name: zmq-rep-mod
    command: ["python", "serverzmq.py"]
    volumes:
      - ../ZMQ-mod:/app:rw

  zmq-req-mod:
    build:
      context: ../ZMQ-mod
      dockerfile: Dockerfile
    container_name: zmq-req-mod
    depends_on:
      - zmq-rep-mod
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ../ZMQ-mod:/app:rw

  zmq-pub-mod:
    build:
      context: ../ZMQ-mod
      dockerfile: Dockerfile
    container_name: zmq-pub-mod
    command: ["python", "pubzmq.py"]
    volumes:
      - ../ZMQ-mod:/app:rw

  zmq-sub-mod:
    build:
      context: ../ZMQ-mod
      dockerfile: Dockerfile
    container_name: zmq-sub-mod
    depends_on:
      - zmq-pub-mod
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ../ZMQ-mod:/app:rw

  zmq-push-mod:
    build:
      context: ../ZMQ-mod
      dockerfile: Dockerfile
    container_name: zmq-push-mod
    command: ["python", "pushzmq-mod.py"]
    volumes:
      - ../ZMQ-mod:/app:rw

  zmq-pull-mod:
    build:
      context: ../ZMQ-mod
      dockerfile: Dockerfile
    container_name: zmq-pull-mod
    depends_on:
      - zmq-push-mod
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ../ZMQ-mod:/app:rw